### ISSUE TITLE
Revisit function naming

### ISSUE THREAD

**Issue by pdil** [pdil/usmap#25]
There are now a lot more functions within `usmap` than when the project was started. There should be some thought given to the naming of these functions going forward (before we reach a stable 1.0 release).

If the functions are to be changed, they will be renamed by `v0.7.0` and the old function names will remain but be deprecated until `v1.0.0` (where they will be removed).

Current Name | Proposed Name
-------------- | ---------------- 
`fips` |
`fips_info` | 
`map_with_data` |
`plot_usmap` |
`usmap_crs` |
`usmap_transform` |
`usmap` |

**Comment by TrashBirdEcology** [comment]
I recommend changing `usmap_transform` to something different that does not include "usmap". This is confusing as it implies I am transforming your map, and not my data frame to conform to your maps.

**Comment by pdil** [comment]
Changed the target release for this change from v0.6.0 to v0.7.0 since `usmapdata` changes are going into v0.6.0. This allows for more separation of large changes between multiple releases.

**Comment by pdil** [comment]
Since it's been so long since I first came up with this idea I've decided to put it on hold since the functions have been named this way for many years at this point and there will be some friction to re-learning any new names, even with a deprecation schedule.

I may revisit this in the future, especially after 1.0 (if `usmap` ever even reaches that version number 🤪).
