### ISSUE TITLE
Plotting a merged data frame

### ISSUE THREAD

**Issue by Edward-McNeil** [pdil/usmap#36]
**Describe the bug**
This used to work in version 0.2.1, now an error is returned.

**To Reproduce**

library(usmap)
library(dplyr)
data(USArrests)
USArrests$full <- rownames(USArrests)
USA50 <- inner_join(us_map(), USArrests)
plot_usmap(data=USA50, values="Murder")
Error in `[.data.frame`(result, , c(setdiff(names(result), names(data)),  : 
  undefined columns selected

**Expected behavior**
A map appearing in the plot window

**Screenshots**

**Smartphone (please complete the following information):**
 - R version: [4.0.0]
 - `usmap` version: [0.5.0]
 - Platform: [Windows]

**Additional context**

**Comment by Edward-McNeil** [comment]
After reading the documentation, I figure it out...

data	
A data frame containing values to plot on the map. This parameter should be a data frame consisting of two columns, a fips code (2 characters for state, 5 characters for county) and the value that should be associated with that region. The columns of data must be fips and the value of the 'values' parameter.

So, the following works after selecting only the required columns after mergin.

```
library(usmap)
library(dplyr)
data(USArrests)
USArrests$full <- rownames(USArrests)
USA50 <- inner_join(us_map(), USArrests) %>% 
    select(fips, Murder) # <--- need to add this line
plot_usmap(data=USA50, values="Murder")
```

**Comment by pdil** [comment]
@Edward-McNeil you should be able to just do the following:

```
library(usmap)

data("USArrests")

USArrests$state <- rownames(USArrests)
plot_usmap(data = USArrests, values = "Murder")
```

The `inner_join` with `us_map()` isn't necessary because as long as the data has a `state` or `fips` column it will be joined to that data during `plot_usmap`. If you pass the full `us_map()` data to `plot_usmap()` it's going to take a lot longer to process because the data set is so large (instead of just being 50 rows).

**Comment by Edward-McNeil** [comment]
Tried that but...
```
> plot_usmap(data=USArrests, values="Murder")
Error in map_with_data(data, values = values, include = include) : 
  * `data` must be a data frame with columns `fips` and `Murder`
  * Make sure the `values` parameter has been set correctly.
```
I read the documentation again:

**data**	
A data frame containing values to plot on the map. This parameter should be a data frame consisting of two columns, a fips code (2 characters for state, 5 characters for county) and the value that should be associated with that region. The columns of data _must_ be fips and the value of the 'values' parameter.

The issue is the fips column. That **MUST** be in the data frame to plot.

But USArrests data frame doesn't have this column. So, I had to merge the builtin "statepop" data frame with the "USArrests" data frame.

```
data(USArrests)
USArrests$full <- rownames(USArrests)  # to facilitate the merge
USMurders <- merge(statepop, USArrests)  # will merge on the "full" column by default
plot_usmap(data=USMurders, values="Murder") # Works. Hooray!
```
