### ISSUE TITLE
What is the coordinate system?

### ISSUE THREAD

**Issue by dicook** [pdil/usmap#41]
The x and y in the US map look like they are UTM. 

Is it possible to get lat long coordinates instead?

**Comment by pdil** [comment]
The coordinates have been transformed from lat/long to what they are now to use a different projection. If you want to plot lat/long points you can convert them using `usmap_transform` and then add them to `plot_usmap` (see the earthquakes example towards the bottom of this page: https://cran.r-project.org/web/packages/usmap/vignettes/advanced-mapping.html).
