### ISSUE TITLE
Plotting both state and county boundaries on same map

### ISSUE THREAD

**Issue by yifeitung** [pdil/usmap#45]
How could I plotting both state and county boundaries on the same map? 

the following codes could run smoothly in the past,

```
counties_df <- us_map(regions = "counties", exclude = c("AK", "HI"))
states_df <- us_map(regions = "states", exclude = c("AK", "HI"))

ggplot() +
  geom_polygon(data = counties_df,
               aes(x = x, y = y, group = group),
               fill = NA, color = "black") +
  geom_polygon(data = states_df,
               aes(x = x, y = y, group = group),
               fill = NA, color = "red") +
  coord_equal()
```

But now the two do not overlap. Is there anyway to fix this? Thank you so much!

![issue](https://user-images.githubusercontent.com/38272447/106302835-73254100-6227-11eb-9793-888f4d00c8a7.png)

**Comment by pdil** [comment]
@yifeitung that's strange, what versions of R and usmap are you using (run `sessionInfo()` and reply with the output)? I can try to reproduce it and see what's going on.

**Comment by yifeitung** [comment]
Here is sessionInfo:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] usmap_0.5.2.9999 forcats_0.5.1    stringr_1.4.0    dplyr_1.0.3      purrr_0.3.4     
 [6] readr_1.4.0      tidyr_1.1.2      tibble_3.0.5     ggplot2_3.3.3    tidyverse_1.3.0 
```
 I used latest usmap that I download directly from repo/

**Comment by pdil** [comment]
Thanks that helps a lot, I must have broken something with the latest change. I think if you use the latest stable version `usmap 0.5.2` it should work. In the mean time I will fix that issue before it becomes a final release.

You can install v0.5.2 with the following:
```
install.packages("usmap")
```
if that doesn't work, try:
```
devtools::install_version("usmap", version = "0.5.2", repos = "http://cran.us.r-project.org")
```

**Comment by yifeitung** [comment]
This works! Thank you!
