### ISSUE TITLE
maptools retiring soon

### ISSUE THREAD

**Issue by rsbivand** [pdil/usmap#57]
See https://r-spatial.org/r/2022/04/12/evolution.html. From pkgapi analysis https://github.com/r-lib/pkgapi, this package uses `elide()` methods, which is used in `R/transform.R`. The `maptools::elide()` methods could be moved to **sp**, but I don't know whether this is worth doing given the restricted use in this package and no detected use elsewhere.

**Comment by cristinamullin** [comment]
Hi, I have a related question/issue. My functions that leverage usmaps seem to work when using usmaps (from github) but not the current cran version. Do you have plans to update usmaps on CRAN soon?

**Comment by cristinamullin** [comment]
This is the error I get with the current CRAN version, which goes away when usmaps is installed directly from GitHub: 
`maptools` must be installed to use `usmap_transform`

**Comment by pdil** [comment]
> This is the error I get with the current CRAN version, which goes away when usmaps is installed directly from GitHub: `maptools` must be installed to use `usmap_transform`

@cristinamullin that's strange, since there haven't been many changes (especially related to mapping code) since the latest 0.6.1 release. Can you run `sessionInfo()` and post it in a new issue so I can take a look?
