### ISSUE TITLE
Missing FIPS 46113: Shannon County / Oglala Lakota County

### ISSUE THREAD

**Issue by mosew** [pdil/usmap#6]
No shapes for this county are contained in the us_counties.csv file.

**Comment by pdil** [comment]
Looks like that county had a name change in May 2015 (shapefile data is as of January 1, 2015). I will update to the 2017 shapefiles.

**Comment by pdil** [comment]
@mosew I’m almost finished updating the shape files to the 2017 versions. However I found that FIPS 46113 no longer exists. It was changed to 46102 when the county was renamed from Shannon County to Oglala County in May 2015.

See http://www.nws.noaa.gov/om/notification/scn15-31shannon_oglalacty%20cca.htm, specifically (emphasis mine):
> …
> Major points to be aware of for NWS products and services:
>  
> The county name will change from Shannon to Oglala Lakota.  The
> existing county boundaries will not change.
>  
> **-The FIPS code changes from 46113 to a 46102.** FIPS codes are
> assigned and maintained by the U.S. Census Bureau.
>  
> -The Universal Geographic Code by County (UGC-C) will change
> from SDC113 to SDC102.
>  
> -The NWS public forecast zone name will change from Shannon to
> Oglala Lakota. The existing UGC by Zone (UGC-Z), SDZ042, remains
> unchanged,
> …

The new shape files will have Oglala Lakota County at FIPS 46102 and Shannon County at FIPS 46113 will be removed.

**Comment by pdil** [comment]
@mosew This is now finished (see [commit a7f2f52](https://github.com/pdil/usmap/commit/a7f2f52a16bee0a23b4fbcfbeb40ead7787a9d71)) and will be included in the next release.

If you can’t wait, use `devtools::install_github(“usmap”)`.

Thanks for bringing this issue to my attention!
