### ISSUE TITLE
Compatibility with geom_text/annotate

### ISSUE THREAD

**Issue by USMortality** [pdil/usmap#74]
**Describe the bug**
I'm trying to add a label to the usmap plot to the top right, but the text always ends up at the same place, regardless of the x/y values. Any ideas?

**To Reproduce**
```
df <- read_csv(system.file("extdata", "county_fips.csv", package = "usmap"))
df$pop_2015 <- 1000
usmap::plot_usmap(
    data = df,
    "counties",
    values = "pop_2015",
    color = NA
) + geom_text(
    x = 0,
    y = 0,
    label = "Top Right Label",
    hjust = 1,
    vjust = 1
) + annotate(
    "text",
    x = 100,
    y = 100,
    label = "Top Right Label #2"
)
```

**Expected behavior**
Be able to add annotate text to the plot.

![plot](https://github.com/pdil/usmap/assets/94856880/f3dc7894-7120-4f3c-bb91-83490308d619)

**Comment by pdil** [comment]
The x, y coordinates of the map that will be used by `geom_text` and `annotate` aren't straightforward to determine. Instead you can use `usmap_transform` to convert longitude/latitude coordinates into ones that will make sense on the map.
